
#define UI_URL "http://rmst.local:3000"

#define WIFI0 "SSID_EXAMPLE_0", "PASSWORD_EXAMPLE_0"
#define WIFI1 "SSID_EXAMPLE_1", "PASSWORD_EXAMPLE_1"
#define WIFI2 "SSID_EXAMPLE_2", "PASSWORD_EXAMPLE_2"